view: words {
  derived_table: {
    sql: SELECT 'beauty' AS word UNION ALL
      SELECT 'foundation' UNION ALL
      SELECT 'organic' UNION ALL
      SELECT 'sample' UNION ALL
      SELECT 'cream' UNION ALL
      SELECT 'compact' UNION ALL
      SELECT 'lip' UNION ALL
      SELECT 'fitglow' UNION ALL
      SELECT 'oil' UNION ALL
      SELECT 'blush' UNION ALL
      SELECT 'full' UNION ALL
      SELECT 'body' UNION ALL
      SELECT 'powder' UNION ALL
      SELECT 'polish' UNION ALL
      SELECT 'nail' UNION ALL
      SELECT 'evolution' UNION ALL
      SELECT 'eyeshadow' UNION ALL
      SELECT 'lipstick' UNION ALL
      SELECT 'premium' UNION ALL
      SELECT 'free' UNION ALL
      SELECT 'size' UNION ALL
      SELECT 'eye' UNION ALL
      SELECT 'vita' UNION ALL
      SELECT 'active' UNION ALL
      SELECT 'refill' UNION ALL
      SELECT 'serum' UNION ALL
      SELECT 'satin' UNION ALL
      SELECT 'pressed' UNION ALL
      SELECT 'natural' UNION ALL
      SELECT 'mineral' UNION ALL
      SELECT 'shadow' UNION ALL
      SELECT 'light' UNION ALL
      SELECT 'vapour' UNION ALL
      SELECT 'concealer' UNION ALL
      SELECT 'travel' UNION ALL
      SELECT 'tenoverten' UNION ALL
      SELECT 'stick' UNION ALL
      SELECT 'matte' UNION ALL
      SELECT 'balm' UNION ALL
      SELECT 'tinted' UNION ALL
      SELECT 'conditioner' UNION ALL
      SELECT 'feed' UNION ALL
      SELECT 'face' UNION ALL
      SELECT 'lovefresh' UNION ALL
      SELECT 'gloss' UNION ALL
      SELECT 'brush' UNION ALL
      SELECT 'multi' UNION ALL
      SELECT 'eight' UNION ALL
      SELECT 'deodorant' UNION ALL
      SELECT 'kahina' UNION ALL
      SELECT 'rose' UNION ALL
      SELECT 'sun' UNION ALL
      SELECT 'vivid' UNION ALL
      SELECT 'luminous' UNION ALL
      SELECT 'cleanser' UNION ALL
      SELECT 'skin' UNION ALL
      SELECT 'pure' UNION ALL
      SELECT 'tint' UNION ALL
      SELECT 'sheer' UNION ALL
      SELECT 'mist' UNION ALL
      SELECT 'water' UNION ALL
      SELECT 'spf' UNION ALL
      SELECT 'shampoo' UNION ALL
      SELECT 'moisturizer' UNION ALL
      SELECT 'medium' UNION ALL
      SELECT 'lavender' UNION ALL
      SELECT 'mask' UNION ALL
      SELECT 'glass' UNION ALL
      SELECT 'bottle' UNION ALL
      SELECT 'shimmer' UNION ALL
      SELECT 'lotion' UNION ALL
      SELECT 'aromatherapy' UNION ALL
      SELECT 'soap' UNION ALL
      SELECT 'neutral' UNION ALL
      SELECT 'gwp' UNION ALL
      SELECT 'cleansing' UNION ALL
      SELECT 'chocolate' UNION ALL
      SELECT 'med' UNION ALL
      SELECT 'mascara' UNION ALL
      SELECT 'facial' UNION ALL
      SELECT 'coverage' UNION ALL
      SELECT 'complete' UNION ALL
      SELECT 'bio' UNION ALL
      SELECT 'bar' UNION ALL
      SELECT 'baby' UNION ALL
      SELECT 'treatment' UNION ALL
      SELECT 'tea' UNION ALL
      SELECT 'nude' UNION ALL
      SELECT 'glow' UNION ALL
      SELECT 'dark' UNION ALL
      SELECT 'bath' UNION ALL
      SELECT 'pink' UNION ALL
      SELECT 'no' UNION ALL
      SELECT 'fair' UNION ALL
      SELECT 'cocoa' UNION ALL
      SELECT 'wax' UNION ALL
      SELECT 'use' UNION ALL
      SELECT 'phytonutri' UNION ALL
      SELECT 'luxurious' UNION ALL
      SELECT 'kit' UNION ALL
      SELECT 'trio' UNION ALL
      SELECT 'schmidt' UNION ALL
      SELECT 'libre' UNION ALL
      SELECT 'hand' UNION ALL
      SELECT 'hair' UNION ALL
      SELECT 'gift' UNION ALL
      SELECT 'elitist' UNION ALL
      SELECT 'deep' UNION ALL
      SELECT 'cheek' UNION ALL
      SELECT 'camouflage' UNION ALL
      SELECT 'with' UNION ALL
      SELECT 'wash' UNION ALL
      SELECT 'perfume' UNION ALL
      SELECT 'for' UNION ALL
      SELECT 'fine' UNION ALL
      SELECT 'bronzer' UNION ALL
      SELECT 'black' UNION ALL
      SELECT 'atmosphere' UNION ALL
      SELECT 'plum' UNION ALL
      SELECT 'lipgloss' UNION ALL
      SELECT 'elixir' UNION ALL
      SELECT 'coconut' UNION ALL
      SELECT 'clay' UNION ALL
      SELECT 'spray' UNION ALL
      SELECT 'sponge' UNION ALL
      SELECT 'silken' UNION ALL
      SELECT 'shave' UNION ALL
      SELECT 'set' UNION ALL
      SELECT 'serenity' UNION ALL
      SELECT 'self' UNION ALL
      SELECT 'rush' UNION ALL
      SELECT 'loose' UNION ALL
      SELECT 'eyeliner' UNION ALL
      SELECT 'encore' UNION ALL
      SELECT 'citrus' UNION ALL
      SELECT 'charcoal' UNION ALL
      SELECT 'card' UNION ALL
      SELECT 'alto' UNION ALL
      SELECT 'universalist' UNION ALL
      SELECT 'sweet' UNION ALL
      SELECT 'scrub' UNION ALL
      SELECT 'radiant' UNION ALL
      SELECT 'perfecting' UNION ALL
      SELECT 'mahalo' UNION ALL
      SELECT 'intimate' UNION ALL
      SELECT 'honey' UNION ALL
      SELECT 'good' UNION ALL
      SELECT 'golden' UNION ALL
      SELECT 'duet' UNION ALL
      SELECT 'day' UNION ALL
      SELECT 'colorstick' UNION ALL
      SELECT 'calm' UNION ALL
      SELECT 'butter' UNION ALL
      SELECT 'beige' UNION ALL
      SELECT 'balancing' UNION ALL
      SELECT 'velluto' UNION ALL
      SELECT 'toner' UNION ALL
      SELECT 'style' UNION ALL
      SELECT 'stella' UNION ALL
      SELECT 'soft' UNION ALL
      SELECT 'narcissist' UNION ALL
      SELECT 'love' UNION ALL
      SELECT 'lime' UNION ALL
      SELECT 'gel' UNION ALL
      SELECT 'focus' UNION ALL
      SELECT 'finishing' UNION ALL
      SELECT 'defining' UNION ALL
      SELECT 'collection' UNION ALL
      SELECT 'aria' UNION ALL
      SELECT 'altruist' UNION ALL
      SELECT 'almond' UNION ALL
      SELECT 'vanilla' UNION ALL
      SELECT 'tree' UNION ALL
      SELECT 'titanium' UNION ALL
      SELECT 'tanner' UNION ALL
      SELECT 'siren' UNION ALL
      SELECT 'rosemary' UNION ALL
      SELECT 'pack' UNION ALL
      SELECT 'oui' UNION ALL
      SELECT 'nourishing' UNION ALL
      SELECT 'liquid' UNION ALL
      SELECT 'lash' UNION ALL
      SELECT 'just' UNION ALL
      SELECT 'jar' UNION ALL
      SELECT 'gold' UNION ALL
      SELECT 'fleur' UNION ALL
      SELECT 'extreme' UNION ALL
      SELECT 'ecobrow' UNION ALL
      SELECT 'dioxide' UNION ALL
      SELECT 'detox' UNION ALL
      SELECT 'definition' UNION ALL
      SELECT 'cool' UNION ALL
      SELECT 'contour' UNION ALL
      SELECT 'candle' UNION ALL
      SELECT 'bliss' UNION ALL
      SELECT 'argan' UNION ALL
      SELECT 'youth' UNION ALL
      SELECT 'white' UNION ALL
      SELECT 'vitamin' UNION ALL
      SELECT 'toning' UNION ALL
      SELECT 'thin' UNION ALL
      SELECT 'tan' UNION ALL
      SELECT 'spearmint' UNION ALL
      SELECT 'sophie' UNION ALL
      SELECT 'recharge' UNION ALL
      SELECT 'radiance' UNION ALL
      SELECT 'protectant' UNION ALL
      SELECT 'pour' UNION ALL
      SELECT 'porcelein' UNION ALL
      SELECT 'paper' UNION ALL
      SELECT 'organics' UNION ALL
      SELECT 'night' UNION ALL
      SELECT 'neroli' UNION ALL
      SELECT 'monde' UNION ALL
      SELECT 'moisture' UNION ALL
      SELECT 'lovely' UNION ALL
      SELECT 'loved' UNION ALL
      SELECT 'like' UNION ALL
      SELECT 'leave' UNION ALL
      SELECT 'joyful' UNION ALL
      SELECT 'heat' UNION ALL
      SELECT 'heart' UNION ALL
      SELECT 'green' UNION ALL
      SELECT 'grapefruit' UNION ALL
      SELECT 'giraffe' UNION ALL
      SELECT 'foaming' UNION ALL
      SELECT 'ends' UNION ALL
      SELECT 'elizabeth' UNION ALL
      SELECT 'dry' UNION ALL
      SELECT 'compacts' UNION ALL
      SELECT 'cloud' UNION ALL
      SELECT 'care' UNION ALL
      SELECT 'blue' UNION ALL
      SELECT 'blossoming' UNION ALL
      SELECT 'blossom' UNION ALL
      SELECT 'bloom' UNION ALL
      SELECT 'blend' UNION ALL
      SELECT 'basic' UNION ALL
      SELECT 'always' UNION ALL
      SELECT 'yarok' UNION ALL
      SELECT 'wipes' UNION ALL
      SELECT 'volume' UNION ALL
      SELECT 'verbena' UNION ALL
      SELECT 'touched' UNION ALL
      SELECT 'tight' UNION ALL
      SELECT 'sugar' UNION ALL
      SELECT 'soapwalla' UNION ALL
      SELECT 'sensitive' UNION ALL
      SELECT 'sea' UNION ALL
      SELECT 'sand' UNION ALL
      SELECT 'roll' UNION ALL
      SELECT 'remover' UNION ALL
      SELECT 'pomegranate' UNION ALL
      SELECT 'people' UNION ALL
      SELECT 'pencil' UNION ALL
      SELECT 'parfum' UNION ALL
      SELECT 'nine' UNION ALL
      SELECT 'milk' UNION ALL
      SELECT 'lover' UNION ALL
      SELECT 'ivory' UNION ALL
      SELECT 'illuminating' UNION ALL
      SELECT 'hold' UNION ALL
      SELECT 'highlighter' UNION ALL
      SELECT 'happy' UNION ALL
      SELECT 'grace' UNION ALL
      SELECT 'flawless' UNION ALL
      SELECT 'essential' UNION ALL
      SELECT 'embrace' UNION ALL
      SELECT 'edible' UNION ALL
      SELECT 'dew' UNION ALL
      SELECT 'desired' UNION ALL
      SELECT 'dehn' UNION ALL
      SELECT 'daily' UNION ALL
      SELECT 'cucumber' UNION ALL
      SELECT 'crayons' UNION ALL
      SELECT 'correct' UNION ALL
      SELECT 'candles' UNION ALL
      SELECT 'bubba' UNION ALL
      SELECT 'brightening' UNION ALL
      SELECT 'belly' UNION ALL
      SELECT 'back' UNION ALL
      SELECT 'aura' UNION ALL
      SELECT 'action' UNION ALL
      SELECT 'ylang' UNION ALL
      SELECT 'wonder' UNION ALL
      SELECT 'unscented' UNION ALL
      SELECT 'tonic' UNION ALL
      SELECT 'tints' UNION ALL
      SELECT 'taupe' UNION ALL
      SELECT 'sustaining' UNION ALL
      SELECT 'super' UNION ALL
      SELECT 'stress' UNION ALL
      SELECT 'starter' UNION ALL
      SELECT 'soothing' UNION ALL
      SELECT 'soothe' UNION ALL
      SELECT 'soak' UNION ALL
      SELECT 'setting' UNION ALL
      SELECT 'roques' UNION ALL
      SELECT 'rich' UNION ALL
      SELECT 'realist' UNION ALL
      SELECT 'qi' UNION ALL
      SELECT 'pro' UNION ALL
      SELECT 'primer' UNION ALL
      SELECT 'prep' UNION ALL
      SELECT 'precious' UNION ALL
      SELECT 'pore' UNION ALL
      SELECT 'passion' UNION ALL
      SELECT 'palette' UNION ALL
      SELECT 'orange' UNION ALL
      SELECT 'muslin' UNION ALL
      SELECT 'mousse' UNION ALL
      SELECT 'mesmerize' UNION ALL
      SELECT 'masque' UNION ALL
      SELECT 'marigold' UNION ALL
      SELECT 'makeup' UNION ALL
      SELECT 'luxury' UNION ALL
      SELECT 'locked' UNION ALL
      SELECT 'lightness' UNION ALL
      SELECT 'lemon' UNION ALL
      SELECT 'leila' UNION ALL
      SELECT 'juniper' UNION ALL
      SELECT 'jane' UNION ALL
      SELECT 'james' UNION ALL
      SELECT 'insect' UNION ALL
      SELECT 'illusion' UNION ALL
      SELECT 'hynt' UNION ALL
      SELECT 'hydrolate' UNION ALL
      SELECT 'hydrating' UNION ALL
      SELECT 'herbal' UNION ALL
      SELECT 'give' UNION ALL
      SELECT 'fresh' UNION ALL
      SELECT 'fragrance' UNION ALL
      SELECT 'fez' UNION ALL
      SELECT 'femme' UNION ALL
      SELECT 'eyebrow' UNION ALL
      SELECT 'expressionist' UNION ALL
      SELECT 'enzyme' UNION ALL
      SELECT 'eau' UNION ALL
      SELECT 'dream' UNION ALL
      SELECT 'donation' UNION ALL
      SELECT 'discovery' UNION ALL
      SELECT 'definers' UNION ALL
      SELECT 'dazzling' UNION ALL
      SELECT 'creamy' UNION ALL
      SELECT 'complex' UNION ALL
      SELECT 'coffee' UNION ALL
      SELECT 'coat' UNION ALL
      SELECT 'cloth' UNION ALL
      SELECT 'cherry' UNION ALL
      SELECT 'brown' UNION ALL
      SELECT 'brow' UNION ALL
      SELECT 'bright' UNION ALL
      SELECT 'botanical' UNION ALL
      SELECT 'berry' UNION ALL
      SELECT 'apricot' UNION ALL
      SELECT 'anti' UNION ALL
      SELECT 'amour' UNION ALL
      SELECT 'abundance' UNION ALL
      SELECT 'wisdom' UNION ALL
      SELECT 'whisper' UNION ALL
      SELECT 'violet' UNION ALL
      SELECT 'vegan' UNION ALL
      SELECT 'translucent' UNION ALL
      SELECT 'top' UNION ALL
      SELECT 'tilly' UNION ALL
      SELECT 'tanning' UNION ALL
      SELECT 'sultry' UNION ALL
      SELECT 'state' UNION ALL
      SELECT 'slate' UNION ALL
      SELECT 'santorini' UNION ALL
      SELECT 'santal' UNION ALL
      SELECT 'salts' UNION ALL
      SELECT 'roots' UNION ALL
      SELECT 'replenishing' UNION ALL
      SELECT 'regenerate' UNION ALL
      SELECT 'refreshing' UNION ALL
      SELECT 'red' UNION ALL
      SELECT 'razor' UNION ALL
      SELECT 'ramla' UNION ALL
      SELECT 'purist' UNION ALL
      SELECT 'plumping' UNION ALL
      SELECT 'peppermint' UNION ALL
      SELECT 'peach' UNION ALL
      SELECT 'one' UNION ALL
      SELECT 'nudist' UNION ALL
      SELECT 'nipple' UNION ALL
      SELECT 'nightfall' UNION ALL
      SELECT 'new' UNION ALL
      SELECT 'nectar' UNION ALL
      SELECT 'morning' UNION ALL
      SELECT 'mini' UNION ALL
      SELECT 'mare' UNION ALL
      SELECT 'magentic' UNION ALL
      SELECT 'liner' UNION ALL
      SELECT 'less' UNION ALL
      SELECT 'layered' UNION ALL
      SELECT 'indulgent' UNION ALL
      SELECT 'indigo' UNION ALL
      SELECT 'illusionist' UNION ALL
      SELECT 'honor' UNION ALL
      SELECT 'henn' UNION ALL
      SELECT 'hanalei' UNION ALL
      SELECT 'goddess' UNION ALL
      SELECT 'ginger' UNION ALL
      SELECT 'geranium' UNION ALL
      SELECT 'flora' UNION ALL
      SELECT 'exfoliating' UNION ALL
      SELECT 'essentials' UNION ALL
      SELECT 'essence' UNION ALL
      SELECT 'english' UNION ALL
      SELECT 'duo' UNION ALL
      SELECT 'dr' UNION ALL
      SELECT 'divine' UNION ALL
      SELECT 'deluxe' UNION ALL
      SELECT 'delicate' UNION ALL
      SELECT 'days' UNION ALL
      SELECT 'conceal' UNION ALL
      SELECT 'complexion' UNION ALL
      SELECT 'comfort' UNION ALL
      SELECT 'colour' UNION ALL
      SELECT 'colorbalm' UNION ALL
      SELECT 'color' UNION ALL
      SELECT 'clear' UNION ALL
      SELECT 'classic' UNION ALL
      SELECT 'chic' UNION ALL
      SELECT 'chestnut' UNION ALL
      SELECT 'charmed' UNION ALL
      SELECT 'chamomile' UNION ALL
      SELECT 'cedarwood' UNION ALL
      SELECT 'calendula' UNION ALL
      SELECT 'bronzed' UNION ALL
      SELECT 'broad' UNION ALL
      SELECT 'brightener' UNION ALL
      SELECT 'brand' UNION ALL
      SELECT 'blending' UNION ALL
      SELECT 'blemish' UNION ALL
      SELECT 'bergamot' UNION ALL
      SELECT 'bell' UNION ALL
      SELECT 'bay' UNION ALL
      SELECT 'balmy' UNION ALL
      SELECT 'balms' UNION ALL
      SELECT 'balance' UNION ALL
      SELECT 'atomizer' UNION ALL
      SELECT 'aromatic' UNION ALL
      SELECT 'antioxidant' UNION ALL
      SELECT 'angelic' UNION ALL
      SELECT 'ageless' UNION ALL
      SELECT 'age' UNION ALL
      SELECT 'adore' UNION ALL
      SELECT 'absolute' UNION ALL
      SELECT 'youthful' UNION ALL
      SELECT 'winter' UNION ALL
      SELECT 'wine' UNION ALL
      SELECT 'wildwoods' UNION ALL
      SELECT 'warm' UNION ALL
      SELECT 'wake' UNION ALL
      SELECT 'voluminous' UNION ALL
      SELECT 'vixen' UNION ALL
      SELECT 'violetta' UNION ALL
      SELECT 'vetiver' UNION ALL
      SELECT 'velvety' UNION ALL
      SELECT 'tulsi' UNION ALL
      SELECT 'truffle' UNION ALL
      SELECT 'tangerine' UNION ALL
      SELECT 'sweetness' UNION ALL
      SELECT 'superfood' UNION ALL
      SELECT 'sunflower' UNION ALL
      SELECT 'suite' UNION ALL
      SELECT 'styling' UNION ALL
      SELECT 'street' UNION ALL
      SELECT 'stratus' UNION ALL
      SELECT 'storm' UNION ALL
      SELECT 'still' UNION ALL
      SELECT 'spot' UNION ALL
      SELECT 'spirulina' UNION ALL
      SELECT 'spectrum' UNION ALL
      SELECT 'sparkling' UNION ALL
      SELECT 'solar' UNION ALL
      SELECT 'soda' UNION ALL
      SELECT 'sleep' UNION ALL
      SELECT 'silk' UNION ALL
      SELECT 'shower' UNION ALL
      SELECT 'shiraz' UNION ALL
      SELECT 'shine' UNION ALL
      SELECT 'shea' UNION ALL
      SELECT 'shaving' UNION ALL
      SELECT 'shannon' UNION ALL
      SELECT 'sesame' UNION ALL
      SELECT 'sensuous' UNION ALL
      SELECT 'seed' UNION ALL
      SELECT 'savior' UNION ALL
      SELECT 'sage' UNION ALL
      SELECT 'rosie' UNION ALL
      SELECT 'rosewater' UNION ALL
      SELECT 'rosehip' UNION ALL
      SELECT 'romance' UNION ALL
      SELECT 'ritual' UNION ALL
      SELECT 'restoratives' UNION ALL
      SELECT 'restorative' UNION ALL
      SELECT 'rescue' UNION ALL
      SELECT 'repellent' UNION ALL
      SELECT 'repellant' UNION ALL
      SELECT 'repair' UNION ALL
      SELECT 'renewing' UNION ALL
      SELECT 'refreshmint' UNION ALL
      SELECT 'redness' UNION ALL
      SELECT 'rebel' UNION ALL
      SELECT 'rare' UNION ALL
      SELECT 'queen' UNION ALL
      SELECT 'quartz' UNION ALL
      SELECT 'purple' UNION ALL
      SELECT 'purity' UNION ALL
      SELECT 'purifying' UNION ALL
      SELECT 'protection' UNION ALL
      SELECT 'prickly' UNION ALL
      SELECT 'pot' UNION ALL
      SELECT 'please' UNION ALL
      SELECT 'pigment' UNION ALL
      SELECT 'petitgrain' UNION ALL
      SELECT 'petal' UNION ALL
      SELECT 'perfetto' UNION ALL
      SELECT 'perfector' UNION ALL
      SELECT 'perfect' UNION ALL
      SELECT 'pepper' UNION ALL
      SELECT 'pele' UNION ALL
      SELECT 'peek' UNION ALL
      SELECT 'pearly' UNION ALL
      SELECT 'pearluster' UNION ALL
      SELECT 'pear' UNION ALL
      SELECT 'passionate' UNION ALL
      SELECT 'original' UNION ALL
      SELECT 'opaque' UNION ALL
      SELECT 'onyx' UNION ALL
      SELECT 'olo' UNION ALL
      SELECT 'olive' UNION ALL
      SELECT 'oats' UNION ALL
      SELECT 'nutrient' UNION ALL
      SELECT 'nutmeg' UNION ALL
      SELECT 'nudie' UNION ALL
      SELECT 'notoriously' UNION ALL
      SELECT 'nocturne' UNION ALL
      SELECT 'naked' UNION ALL
      SELECT 'multitasking' UNION ALL
      SELECT 'mulberry' UNION ALL
      SELECT 'move' UNION ALL
      SELECT 'moroccan' UNION ALL
      SELECT 'mocha' UNION ALL
      SELECT 'mirage' UNION ALL
      SELECT 'mint' UNION ALL
      SELECT 'mimosa' UNION ALL
      SELECT 'microderma' UNION ALL
      SELECT 'melon' UNION ALL
      SELECT 'mauve' UNION ALL
      SELECT 'marine' UNION ALL
      SELECT 'mama''s' UNION ALL
      SELECT 'luna' UNION ALL
      SELECT 'lumiere' UNION ALL
      SELECT 'lovina' UNION ALL
      SELECT 'locks' UNION ALL
      SELECT 'lite' UNION ALL
      SELECT 'lilac' UNION ALL
      SELECT 'lavendar' UNION ALL
      SELECT 'kits' UNION ALL
      SELECT 'kabuki' UNION ALL
      SELECT 'jungle' UNION ALL
      SELECT 'joy' UNION ALL
      SELECT 'issue' UNION ALL
      SELECT 'isa''s' UNION ALL
      SELECT 'instant' UNION ALL
      SELECT 'ink' UNION ALL
      SELECT 'infusion' UNION ALL
      SELECT 'illuminator' UNION ALL
      SELECT 'illume' UNION ALL
      SELECT 'iko' UNION ALL
      SELECT 'hypnotist' UNION ALL
      SELECT 'houston' UNION ALL
      SELECT 'horse' UNION ALL
      SELECT 'holiday' UNION ALL
      SELECT 'hippxfive' UNION ALL
      SELECT 'high' UNION ALL
      SELECT 'heavenly' UNION ALL
      SELECT 'healthy' UNION ALL
      SELECT 'gobi' UNION ALL
      SELECT 'glory' UNION ALL
      SELECT 'garnet' UNION ALL
      SELECT 'fund' UNION ALL
      SELECT 'french' UNION ALL
      SELECT 'forte' UNION ALL
      SELECT 'formula' UNION ALL
      SELECT 'floz' UNION ALL
      SELECT 'five' UNION ALL
      SELECT 'firming' UNION ALL
      SELECT 'fig' UNION ALL
      SELECT 'fervor' UNION ALL
      SELECT 'fatale' UNION ALL
      SELECT 'eyepencil' UNION ALL
      SELECT 'exfoliator' UNION ALL
      SELECT 'essasouria' UNION ALL
      SELECT 'espresso' UNION ALL
      SELECT 'enhancing' UNION ALL
      SELECT 'energy' UNION ALL
      SELECT 'energize' UNION ALL
      SELECT 'empower' UNION ALL
      SELECT 'elde' UNION ALL
      SELECT 'eden' UNION ALL
      SELECT 'easy' UNION ALL
      SELECT 'earthy' UNION ALL
      SELECT 'drenched' UNION ALL
      SELECT 'disguise' UNION ALL
      SELECT 'diaper' UNION ALL
      SELECT 'cupcake' UNION ALL
      SELECT 'crystal' UNION ALL
      SELECT 'creams' UNION ALL
      SELECT 'cranberry' UNION ALL
      SELECT 'cosmetics' UNION ALL
      SELECT 'copper' UNION ALL
      SELECT 'cocoon' UNION ALL
      SELECT 'coco' UNION ALL
      SELECT 'cinder' UNION ALL
      SELECT 'chili' UNION ALL
      SELECT 'chia' UNION ALL
      SELECT 'chesnut' UNION ALL
      SELECT 'charlotte' UNION ALL
      SELECT 'champagne' UNION ALL
      SELECT 'cascadia' UNION ALL
      SELECT 'captivate' UNION ALL
      SELECT 'capitalist' UNION ALL
      SELECT 'calming' UNION ALL
      SELECT 'caffeinated' UNION ALL
      SELECT 'burgundy' UNION ALL
      SELECT 'bronzers' UNION ALL
      SELECT 'bowl' UNION ALL
      SELECT 'bottega' UNION ALL
      SELECT 'boosting' UNION ALL
      SELECT 'birch' UNION ALL
      SELECT 'bioactive' UNION ALL
      SELECT 'beyond' UNION ALL
      SELECT 'believe' UNION ALL
      SELECT 'base' UNION ALL
      SELECT 'bang' UNION ALL
      SELECT 'bamboo' UNION ALL
      SELECT 'baking' UNION ALL
      SELECT 'bags' UNION ALL
      SELECT 'auburn' UNION ALL
      SELECT 'aspen' UNION ALL
      SELECT 'around' UNION ALL
      SELECT 'aroma' UNION ALL
      SELECT 'arabian' UNION ALL
      SELECT 'antique' UNION ALL
      SELECT 'angle' UNION ALL
      SELECT 'aging' UNION ALL
      SELECT 'adhesive' UNION ALL
      SELECT 'activated' UNION ALL
      SELECT 'acne' UNION ALL
      SELECT 'above' UNION ALL
      SELECT 'zephyr' UNION ALL
      SELECT 'worth' UNION ALL
      SELECT 'wort' UNION ALL
      SELECT 'world' UNION ALL
      SELECT 'women' UNION ALL
      SELECT 'witch' UNION ALL
      SELECT 'willow' UNION ALL
      SELECT 'wild' UNION ALL
      SELECT 'whip' UNION ALL
      SELECT 'welfare' UNION ALL
      SELECT 'weekend' UNION ALL
      SELECT 'week' UNION ALL
      SELECT 'wedding' UNION ALL
      SELECT 'watts' UNION ALL
      SELECT 'washington' UNION ALL
      SELECT 'wall' UNION ALL
      SELECT 'volumizing' UNION ALL
      SELECT 'voila' UNION ALL
      SELECT 'vivacious' UNION ALL
      SELECT 'vitamins' UNION ALL
      SELECT 'very' UNION ALL
      SELECT 'versailles' UNION ALL
      SELECT 'velvet' UNION ALL
      SELECT 'vacation' UNION ALL
      SELECT 'universal' UNION ALL
      SELECT 'undone' UNION ALL
      SELECT 'unbalanced' UNION ALL
      SELECT 'ultra' UNION ALL
      SELECT 'ultimate' UNION ALL
      SELECT 'two' UNION ALL
      SELECT 'twilight' UNION ALL
      SELECT 'tularosa' UNION ALL
      SELECT 'tub' UNION ALL
      SELECT 'tropez' UNION ALL
      SELECT 'trinidad' UNION ALL
      SELECT 'trial' UNION ALL
      SELECT 'transparent' UNION ALL
      SELECT 'transcend' UNION ALL
      SELECT 'tourmaline' UNION ALL
      SELECT 'toothpaste' UNION ALL
      SELECT 'tonique' UNION ALL
      SELECT 'together' UNION ALL
      SELECT 'timeless' UNION ALL
      SELECT 'time' UNION ALL
      SELECT 'tigereye' UNION ALL
      SELECT 'tie' UNION ALL
      SELECT 'tickle' UNION ALL
      SELECT 'thoughtfully' UNION ALL
      SELECT 'these' UNION ALL
      SELECT 'tester' UNION ALL
      SELECT 'tenderly' UNION ALL
      SELECT 'tell' UNION ALL
      SELECT 'teddy' UNION ALL
      SELECT 'tawny' UNION ALL
      SELECT 'tasting' UNION ALL
      SELECT 'tapered' UNION ALL
      SELECT 'takara' UNION ALL
      SELECT 'system' UNION ALL
      SELECT 'sway' UNION ALL
      SELECT 'surprise' UNION ALL
      SELECT 'supercritical' UNION ALL
      SELECT 'sunshine' UNION ALL
      SELECT 'sunset' UNION ALL
      SELECT 'sunglow' UNION ALL
      SELECT 'summer' UNION ALL
      SELECT 'stuff' UNION ALL
      SELECT 'strike' UNION ALL
      SELECT 'striiike' UNION ALL
      SELECT 'stretch' UNION ALL
      SELECT 'strawberry' UNION ALL
      SELECT 'stain' UNION ALL
      SELECT 'spruce' UNION ALL
      SELECT 'springs' UNION ALL
      SELECT 'spring' UNION ALL
      SELECT 'spin' UNION ALL
      SELECT 'sphere' UNION ALL
      SELECT 'spell' UNION ALL
      SELECT 'spark' UNION ALL
      SELECT 'spa' UNION ALL
      SELECT 'soy' UNION ALL
      SELECT 'sos' UNION ALL
      SELECT 'solver' UNION ALL
      SELECT 'solution' UNION ALL
      SELECT 'soiree' UNION ALL
      SELECT 'soho' UNION ALL
      SELECT 'society' UNION ALL
      SELECT 'socialite' UNION ALL
      SELECT 'snowflower' UNION ALL
      SELECT 'sneek' UNION ALL
      SELECT 'smooth' UNION ALL
      SELECT 'sized' UNION ALL
      SELECT 'simple' UNION ALL
      SELECT 'simmer' UNION ALL
      SELECT 'sigh' UNION ALL
      SELECT 'show' UNION ALL
      SELECT 'shock' UNION ALL
      SELECT 'shield' UNION ALL
      SELECT 'shepherd' UNION ALL
      SELECT 'shell' UNION ALL
      SELECT 'she' UNION ALL
      SELECT 'sharpener' UNION ALL
      SELECT 'sharon' UNION ALL
      SELECT 'shadowplay' UNION ALL
      SELECT 'seduction' UNION ALL
      SELECT 'sedona' UNION ALL
      SELECT 'seashell' UNION ALL
      SELECT 'seabuck' UNION ALL
      SELECT 'sculpt' UNION ALL
      SELECT 'scout' UNION ALL
      SELECT 'schmidts' UNION ALL
      SELECT 'scalp' UNION ALL
      SELECT 'sassy' UNION ALL
      SELECT 'santo' UNION ALL
      SELECT 'salvia' UNION ALL
      SELECT 'salve' UNION ALL
      SELECT 'salt' UNION ALL
      SELECT 'salmon' UNION ALL
      SELECT 'sahara' UNION ALL
      SELECT 'saffron' UNION ALL
      SELECT 'ryan' UNION ALL
      SELECT 'ruby' UNION ALL
      SELECT 'royal' UNION ALL
      SELECT 'rosewood' UNION ALL
      SELECT 'room' UNION ALL
      SELECT 'rollerball' UNION ALL
      SELECT 'rivington' UNION ALL
      SELECT 'riviera' UNION ALL
      SELECT 'rita' UNION ALL
      SELECT 'rinse' UNION ALL
      SELECT 'rice' UNION ALL
      SELECT 'rhapsody' UNION ALL
      SELECT 'rgb' UNION ALL
      SELECT 'revuvenating' UNION ALL
      SELECT 'revitalizing' UNION ALL
      SELECT 'revitalize' UNION ALL
      SELECT 'resurrection' UNION ALL
      SELECT 'restore' UNION ALL
      SELECT 'reset' UNION ALL
      SELECT 'renewal' UNION ALL
      SELECT 'remedy' UNION ALL
      SELECT 'relief' UNION ALL
      SELECT 'rejuvenating' UNION ALL
      SELECT 'regenerating' UNION ALL
      SELECT 'refresh' UNION ALL
      SELECT 'refills' UNION ALL
      SELECT 'reece' UNION ALL
      SELECT 'recover' UNION ALL
      SELECT 'rebalancing' UNION ALL
      SELECT 'rebalance' UNION ALL
      SELECT 'reade' UNION ALL
      SELECT 'raysspf' UNION ALL
      SELECT 'rays' UNION ALL
      SELECT 'raven' UNION ALL
      SELECT 'rapture' UNION ALL
      SELECT 'rainforest' UNION ALL
      SELECT 'rabbit' UNION ALL
      SELECT 'put' UNION ALL
      SELECT 'purfiy' UNION ALL
      SELECT 'puff' UNION ALL
      SELECT 'prtty' UNION ALL
      SELECT 'problem' UNION ALL
      SELECT 'prince' UNION ALL
      SELECT 'prime' UNION ALL
      SELECT 'prima' UNION ALL
      SELECT 'prevention' UNION ALL
      SELECT 'pretty' UNION ALL
      SELECT 'preservation' UNION ALL
      SELECT 'possess' UNION ALL
      SELECT 'portofino' UNION ALL
      SELECT 'poppy' UNION ALL
      SELECT 'pool' UNION ALL
      SELECT 'pointed' UNION ALL
      SELECT 'plant' UNION ALL
      SELECT 'plankton' UNION ALL
      SELECT 'plain' UNION ALL
      SELECT 'pixie' UNION ALL
      SELECT 'pistachio' UNION ALL
      SELECT 'pinup' UNION ALL
      SELECT 'pinot' UNION ALL
      SELECT 'picture' UNION ALL
      SELECT 'peony' UNION ALL
      SELECT 'peonies' UNION ALL
      SELECT 'penelope' UNION ALL
      SELECT 'peel' UNION ALL
      SELECT 'pecan' UNION ALL
      SELECT 'peaushun' UNION ALL
      SELECT 'peacock' UNION ALL
      SELECT 'patchouli' UNION ALL
      SELECT 'party' UNION ALL
      SELECT 'paris' UNION ALL
      SELECT 'paradise' UNION ALL
      SELECT 'paprika' UNION ALL
      SELECT 'papparazi' UNION ALL
      SELECT 'paparazzi' UNION ALL
      SELECT 'palo' UNION ALL
      SELECT 'pale' UNION ALL
      SELECT 'overnight' UNION ALL
      SELECT 'out' UNION ALL
      SELECT 'orchard' UNION ALL
      SELECT 'omega' UNION ALL
      SELECT 'oat' UNION ALL
      SELECT 'now' UNION ALL
      SELECT 'nourish' UNION ALL
      SELECT 'nolita' UNION ALL
      SELECT 'nobody''s' UNION ALL
      SELECT 'nights' UNION ALL
      SELECT 'nighclubbing' UNION ALL
      SELECT 'next' UNION ALL
      SELECT 'neon' UNION ALL
      SELECT 'neck' UNION ALL
      SELECT 'navy' UNION ALL
      SELECT 'naughty' UNION ALL
      SELECT 'nature' UNION ALL
      SELECT 'nasal' UNION ALL
      SELECT 'myth' UNION ALL
      SELECT 'murray' UNION ALL
      SELECT 'muriwai' UNION ALL
      SELECT 'mud' UNION ALL
      SELECT 'moss' UNION ALL
      SELECT 'moonstone' UNION ALL
      SELECT 'moonlight' UNION ALL
      SELECT 'moondance' UNION ALL
      SELECT 'moon' UNION ALL
      SELECT 'monroe' UNION ALL
      SELECT 'monaco' UNION ALL
      SELECT 'mojave' UNION ALL
      SELECT 'moisturizing' UNION ALL
      SELECT 'modern' UNION ALL
      SELECT 'mitt' UNION ALL
      SELECT 'minerals' UNION ALL
      SELECT 'mina' UNION ALL
      SELECT 'milky' UNION ALL
      SELECT 'midnight' UNION ALL
      SELECT 'micrograins' UNION ALL
      SELECT 'micro' UNION ALL
      SELECT 'mica' UNION ALL
      SELECT 'mesmerizing' UNION ALL
      SELECT 'merry' UNION ALL
      SELECT 'mermaid' UNION ALL
      SELECT 'mer' UNION ALL
      SELECT 'menu' UNION ALL
      SELECT 'meli' UNION ALL
      SELECT 'mega' UNION ALL
      SELECT 'may' UNION ALL
      SELECT 'max' UNION ALL
      SELECT 'mauna' UNION ALL
      SELECT 'matcha' UNION ALL
      SELECT 'massage' UNION ALL
      SELECT 'mark' UNION ALL
      SELECT 'marilyn' UNION ALL
      SELECT 'maracuja' UNION ALL
      SELECT 'maracaibo' UNION ALL
      SELECT 'mandarin' UNION ALL
      SELECT 'mallow' UNION ALL
      SELECT 'make' UNION ALL
      SELECT 'majorca' UNION ALL
      SELECT 'maiden' UNION ALL
      SELECT 'mahina' UNION ALL
      SELECT 'magazine' UNION ALL
      SELECT 'mae' UNION ALL
      SELECT 'madam' UNION ALL
      SELECT 'macao' UNION ALL
      SELECT 'maca' UNION ALL
      SELECT 'lycopene' UNION ALL
      SELECT 'lumina' UNION ALL
      SELECT 'ludlow' UNION ALL
      SELECT 'lucy''s' UNION ALL
      SELECT 'lover''s' UNION ALL
      SELECT 'loud' UNION ALL
      SELECT 'london' UNION ALL
      SELECT 'loa' UNION ALL
      SELECT 'liz' UNION ALL
      SELECT 'lips' UNION ALL
      SELECT 'lipid' UNION ALL
      SELECT 'linen' UNION ALL
      SELECT 'lindstrom' UNION ALL
      SELECT 'limited' UNION ALL
      SELECT 'lilfox' UNION ALL
      SELECT 'life' UNION ALL
      SELECT 'liberty' UNION ALL
      SELECT 'leigh' UNION ALL
      SELECT 'leahlani' UNION ALL
      SELECT 'leaf' UNION ALL
      SELECT 'laughing' UNION ALL
      SELECT 'last' UNION ALL
      SELECT 'large' UNION ALL
      SELECT 'lady' UNION ALL
      SELECT 'kvetch' UNION ALL
      SELECT 'kokomo' UNION ALL
      SELECT 'kokoleka' UNION ALL
      SELECT 'koi' UNION ALL
      SELECT 'knights' UNION ALL
      SELECT 'kitten' UNION ALL
      SELECT 'kessa' UNION ALL
      SELECT 'kennedy' UNION ALL
      SELECT 'keiko' UNION ALL
      SELECT 'kashmir' UNION ALL
      SELECT 'karma' UNION ALL
      SELECT 'kalima' UNION ALL
      SELECT 'kalahari' UNION ALL
      SELECT 'kafir' UNION ALL
      SELECT 'jump' UNION ALL
      SELECT 'julep' UNION ALL
      SELECT 'johns' UNION ALL
      SELECT 'jelly' UNION ALL
      SELECT 'jasmine' UNION ALL
      SELECT 'japanese' UNION ALL
      SELECT 'jam' UNION ALL
      SELECT 'iridescent' UNION ALL
      SELECT 'intuition' UNION ALL
      SELECT 'international' UNION ALL
      SELECT 'intensive' UNION ALL
      SELECT 'ingrown' UNION ALL
      SELECT 'infused' UNION ALL
      SELECT 'inflorescence' UNION ALL
      SELECT 'incognito' UNION ALL
      SELECT 'impulse' UNION ALL
      SELECT 'immortelle' UNION ALL
      SELECT 'illuminate' UNION ALL
      SELECT 'icon' UNION ALL
      SELECT 'ice' UNION ALL
      SELECT 'humble' UNION ALL
      SELECT 'hudson' UNION ALL
      SELECT 'hot' UNION ALL
      SELECT 'honeysuckle' UNION ALL
      SELECT 'hollybeth' UNION ALL
      SELECT 'hint' UNION ALL
      SELECT 'hilight' UNION ALL
      SELECT 'higher' UNION ALL
      SELECT 'hepburn' UNION ALL
      SELECT 'henae' UNION ALL
      SELECT 'hellebere' UNION ALL
      SELECT 'heartbeat' UNION ALL
      SELECT 'healing' UNION ALL
      SELECT 'headache' UNION ALL
      SELECT 'hazel' UNION ALL
      SELECT 'havana' UNION ALL
      SELECT 'harlow' UNION ALL
      SELECT 'hanae' UNION ALL
      SELECT 'haenkei' UNION ALL
      SELECT 'gypsy' UNION ALL
      SELECT 'grits' UNION ALL
      SELECT 'greeting' UNION ALL
      SELECT 'grand' UNION ALL
      SELECT 'goat' UNION ALL
      SELECT 'global' UNION ALL
      SELECT 'glitz' UNION ALL
      SELECT 'girl' UNION ALL
      SELECT 'gilded' UNION ALL
      SELECT 'gentlemans' UNION ALL
      SELECT 'generation' UNION ALL
      SELECT 'gardenia' UNION ALL
      SELECT 'garden' UNION ALL
      SELECT 'funnel' UNION ALL
      SELECT 'fulton' UNION ALL
      SELECT 'frozen' UNION ALL
      SELECT 'friend' UNION ALL
      SELECT 'frida' UNION ALL
      SELECT 'freja' UNION ALL
      SELECT 'frais' UNION ALL
      SELECT 'fragrances' UNION ALL
      SELECT 'forever' UNION ALL
      SELECT 'forest' UNION ALL
      SELECT 'fly' UNION ALL
      SELECT 'flushed' UNION ALL
      SELECT 'flush' UNION ALL
      SELECT 'flourish' UNION ALL
      SELECT 'floral' UNION ALL
      SELECT 'flocked' UNION ALL
      SELECT 'flight' UNION ALL
      SELECT 'flax' UNION ALL
      SELECT 'flat' UNION ALL
      SELECT 'flash' UNION ALL
      SELECT 'flare' UNION ALL
      SELECT 'fierce' UNION ALL
      SELECT 'fields' UNION ALL
      SELECT 'feisty' UNION ALL
      SELECT 'fast' UNION ALL
      SELECT 'fashion' UNION ALL
      SELECT 'eyelash' UNION ALL
      SELECT 'exotic' UNION ALL
      SELECT 'exfoliant' UNION ALL
      SELECT 'everything' UNION ALL
      SELECT 'everyday' UNION ALL
      SELECT 'ever' UNION ALL
      SELECT 'evening' UNION ALL
      SELECT 'eucalyptus' UNION ALL
      SELECT 'eternal' UNION ALL
      SELECT 'essex' UNION ALL
      SELECT 'essaouira' UNION ALL
      SELECT 'envision' UNION ALL
      SELECT 'enriching' UNION ALL
      SELECT 'enhancer' UNION ALL
      SELECT 'energising' UNION ALL
      SELECT 'enchanted' UNION ALL
      SELECT 'elves' UNION ALL
      SELECT 'elements' UNION ALL
      SELECT 'eggplant' UNION ALL
      SELECT 'edition' UNION ALL
      SELECT 'echo' UNION ALL
      SELECT 'ebony' UNION ALL
      SELECT 'earhart' UNION ALL
      SELECT 'dusty' UNION ALL
      SELECT 'dust' UNION ALL
      SELECT 'drying' UNION ALL
      SELECT 'drama' UNION ALL
      SELECT 'dolce' UNION ALL
      SELECT 'dizzy' UNION ALL
      SELECT 'diva' UNION ALL
      SELECT 'dirt' UNION ALL
      SELECT 'digital' UNION ALL
      SELECT 'diamonds' UNION ALL
      SELECT 'diamond' UNION ALL
      SELECT 'detoxifying' UNION ALL
      SELECT 'dessert' UNION ALL
      SELECT 'desire' UNION ALL
      SELECT 'desert' UNION ALL
      SELECT 'depth' UNION ALL
      SELECT 'delish' UNION ALL
      SELECT 'delicious' UNION ALL
      SELECT 'delancy' UNION ALL
      SELECT 'defense' UNION ALL
      SELECT 'davids' UNION ALL
      SELECT 'daughter' UNION ALL
      SELECT 'date' UNION ALL
      SELECT 'daphne' UNION ALL
      SELECT 'dancer' UNION ALL
      SELECT 'cuticle' UNION ALL
      SELECT 'curls' UNION ALL
      SELECT 'curler' UNION ALL
      SELECT 'crushed' UNION ALL
      SELECT 'crimson' UNION ALL
      SELECT 'creme' UNION ALL
      SELECT 'crease' UNION ALL
      SELECT 'craze' UNION ALL
      SELECT 'courage' UNION ALL
      SELECT 'cosmopolitan' UNION ALL
      SELECT 'cosmic' UNION ALL
      SELECT 'core' UNION ALL
      SELECT 'coral' UNION ALL
      SELECT 'coquette' UNION ALL
      SELECT 'conservation' UNION ALL
      SELECT 'conservancy' UNION ALL
      SELECT 'consent' UNION ALL
      SELECT 'comb' UNION ALL
      SELECT 'clutch' UNION ALL
      SELECT 'clover' UNION ALL
      SELECT 'cliff' UNION ALL
      SELECT 'clearing' UNION ALL
      SELECT 'clean' UNION ALL
      SELECT 'clarity' UNION ALL
      SELECT 'citrine' UNION ALL
      SELECT 'circle' UNION ALL
      SELECT 'cinnamon' UNION ALL
      SELECT 'church' UNION ALL
      SELECT 'chrome' UNION ALL
      SELECT 'christie' UNION ALL
      SELECT 'choice' UNION ALL
      SELECT 'chlorophyll' UNION ALL
      SELECT 'child' UNION ALL
      SELECT 'chiffon' UNION ALL
      SELECT 'chichi' UNION ALL
      SELECT 'chianti' UNION ALL
      SELECT 'cheeky' UNION ALL
      SELECT 'charm' UNION ALL
      SELECT 'chamomilla' UNION ALL
      SELECT 'chameleon' UNION ALL
      SELECT 'cerise' UNION ALL
      SELECT 'cellular' UNION ALL
      SELECT 'celebrity' UNION ALL
      SELECT 'cedar' UNION ALL
      SELECT 'catalyst' UNION ALL
      SELECT 'cassava' UNION ALL
      SELECT 'carnation' UNION ALL
      SELECT 'carmine' UNION ALL
      SELECT 'cardamom' UNION ALL
      SELECT 'canyon' UNION ALL
      SELECT 'camo' UNION ALL
      SELECT 'camel' UNION ALL
      SELECT 'call' UNION ALL
      SELECT 'buzz' UNION ALL
      SELECT 'buttoned' UNION ALL
      SELECT 'butterfly' UNION ALL
      SELECT 'buttercup' UNION ALL
      SELECT 'bundle' UNION ALL
      SELECT 'buck' UNION ALL
      SELECT 'bubble' UNION ALL
      SELECT 'brushes' UNION ALL
      SELECT 'bronze' UNION ALL
      SELECT 'breathe' UNION ALL
      SELECT 'breast' UNION ALL
      SELECT 'brazilian' UNION ALL
      SELECT 'bran' UNION ALL
      SELECT 'boy' UNION ALL
      SELECT 'box' UNION ALL
      SELECT 'bouquet' UNION ALL
      SELECT 'bottom' UNION ALL
      SELECT 'boo' UNION ALL
      SELECT 'bombora' UNION ALL
      SELECT 'bohemian' UNION ALL
      SELECT 'blond' UNION ALL
      SELECT 'bless' UNION ALL
      SELECT 'blender' UNION ALL
      SELECT 'bikini' UNION ALL
      SELECT 'between' UNION ALL
      SELECT 'berrylicious' UNION ALL
      SELECT 'beloved' UNION ALL
      SELECT 'belle' UNION ALL
      SELECT 'beldi' UNION ALL
      SELECT 'beekman' UNION ALL
      SELECT 'bedtime' UNION ALL
      SELECT 'beautifying' UNION ALL
      SELECT 'beautiful' UNION ALL
      SELECT 'bean' UNION ALL
      SELECT 'beach' UNION ALL
      SELECT 'baxter' UNION ALL
      SELECT 'bathing' UNION ALL
      SELECT 'basics' UNION ALL
      SELECT 'bark' UNION ALL
      SELECT 'bardot' UNION ALL
      SELECT 'baobab' UNION ALL
      SELECT 'bambi' UNION ALL
      SELECT 'balloons' UNION ALL
      SELECT 'bag' UNION ALL
      SELECT 'ayour' UNION ALL
      SELECT 'aubergine' UNION ALL
      SELECT 'asphalt' UNION ALL
      SELECT 'arthouse' UNION ALL
      SELECT 'arctic' UNION ALL
      SELECT 'apple' UNION ALL
      SELECT 'aphrodite' UNION ALL
      SELECT 'antioxident' UNION ALL
      SELECT 'animal' UNION ALL
      SELECT 'angel' UNION ALL
      SELECT 'anarose' UNION ALL
      SELECT 'amethyst' UNION ALL
      SELECT 'ambrosia' UNION ALL
      SELECT 'amber' UNION ALL
      SELECT 'amazon' UNION ALL
      SELECT 'amazed' UNION ALL
      SELECT 'alps' UNION ALL
      SELECT 'aloha' UNION ALL
      SELECT 'alluring' UNION ALL
      SELECT 'allure' UNION ALL
      SELECT 'allover' UNION ALL
      SELECT 'alkaitis' UNION ALL
      SELECT 'aknari' UNION ALL
      SELECT 'affair' UNION ALL
      SELECT 'activate' UNION ALL
      SELECT 'acetone' UNION ALL
      SELECT 'ace' UNION ALL
      SELECT 'ritual'
       ;;
      sql_trigger_value: SELECT 1 ;;
      indexes: ["word"]
  }

  dimension: word {
    type: string
    primary_key: yes
    sql: ${TABLE}.word ;;
  }

}
